# Generated by Django 5.2.5 on 2025-08-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
