# Generated by Django 5.2.5 on 2025-09-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_customuser_authored_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="journalist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_users",
                to="articles.journalist",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_users",
                to="articles.publisher",
            ),
        ),
    ]
