# Generated by Django 5.2.5 on 2025-09-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_subscription_journalist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="publisher",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="journalist",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Newsletter",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
